spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cohort24
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true